spring:
  application:
    name: Fit4Ever
  datasource:
    url: jdbc:h2:mem:fit4everdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"

server:
  port: 8080

# Swagger UI available at /swagger-ui.html
